window_width: 1920
window_height: 1080
ant_count: 500
ant_speed: 0.5
ant_scale: 0.1
animation_speed: 0.04  # seconds per frame (higher = slower legs)

pheromone_size: 2
decay_rate: 0.002

# Catppuccin Macchiato Theme
background_color: [36, 39, 58]    # Base
ant_color:        [183, 189, 248] # Lavender
nest_color:       [255, 255, 255] # White
food_color:       [166, 218, 149] # Green
pheromone_to_food_color: [245, 169, 127]  # Peach (Returning state)
pheromone_to_nest_color: [138, 173, 244]  # Blue (Searching state)